spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/Database/h2/securityDB
      driver-class-name: org.h2.Driver
      username: sa
      password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  h2:
    console:
      enabled: true

logging:
  level:
    root: info